-- HNBT Inventory Management - employee activity audit trail
-- Run once in the Supabase SQL Editor before enabling the Audit Log UI.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_name text,
  branch text,
  old_value jsonb,
  new_value jsonb,
  details text
);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);
alter table public.audit_logs enable row level security;
-- Current app uses the Supabase anon client behind the authenticated Vercel application session.
-- Allow reading/inserting audit rows, but intentionally provide NO update/delete policy.
drop policy if exists "audit_logs_read" on public.audit_logs;
create policy "audit_logs_read" on public.audit_logs for select to anon using (true);
drop policy if exists "audit_logs_insert" on public.audit_logs;
create policy "audit_logs_insert" on public.audit_logs for insert to anon with check (true);
revoke update, delete on public.audit_logs from anon;
grant select, insert on public.audit_logs to anon;
