import { createClient } from "@supabase/supabase-js";

export function getSupabaseCredentials() {
  const envUrl = import.meta.env.VITE_SUPABASE_URL;
  const envKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
  const localUrl = localStorage.getItem("hb_supabase_url") || "";
  const localKey = localStorage.getItem("hb_supabase_key") || "";
  return { url:(envUrl || localUrl || "").trim(), key:(envKey || localKey || "").trim(), isEnv:Boolean(envUrl && envKey) };
}
let cachedClient=null,lastUrl="",lastKey="";
export function getSupabase(){const{url,key}=getSupabaseCredentials();if(!url||!key)return null;if(cachedClient&&lastUrl===url&&lastKey===key)return cachedClient;try{cachedClient=createClient(url,key);lastUrl=url;lastKey=key;return cachedClient}catch(err){console.error("Failed to initialize Supabase client:",err);return null}}
export function isSupabaseConfigured(){const{url,key}=getSupabaseCredentials();return Boolean(url&&key)}
export function saveSupabaseCredentials(url,key){if(url)localStorage.setItem("hb_supabase_url",url.trim());else localStorage.removeItem("hb_supabase_url");if(key)localStorage.setItem("hb_supabase_key",key.trim());else localStorage.removeItem("hb_supabase_key");cachedClient=null;lastUrl="";lastKey=""}

// Multi-user Supabase Auth helpers
export async function signInEmployee(email,password){const s=getSupabase();if(!s)throw new Error("Supabase is not configured.");const{data,error}=await s.auth.signInWithPassword({email:String(email).trim(),password:String(password)});if(error)throw error;const profile=await fetchEmployeeProfile(data.user.id);if(!profile)throw new Error("Employee profile is not configured.");if(profile.active===false){await s.auth.signOut();throw new Error("This employee account has been disabled.");}return{user:data.user,profile}}
export async function signOutEmployee(){const s=getSupabase();if(!s)return;await s.auth.signOut()}
export async function getEmployeeSession(){const s=getSupabase();if(!s)return null;const{data,error}=await s.auth.getSession();if(error||!data?.session?.user)return null;const profile=await fetchEmployeeProfile(data.session.user.id);if(!profile||profile.active===false)return null;return{session:data.session,user:data.session.user,profile}}
export async function fetchEmployeeProfile(userId){const s=getSupabase();if(!s||!userId)return null;const{data,error}=await s.from("employee_profiles").select("*").eq("user_id",userId).maybeSingle();if(error)throw error;return data||null}
export async function fetchEmployeeProfiles(){const s=getSupabase();if(!s)return[];const{data,error}=await s.from("employee_profiles").select("*").order("full_name");if(error)throw error;return data||[]}
export async function updateEmployeeProfile(userId,changes){const s=getSupabase();if(!s)return false;const allowed={};for(const k of ["full_name","role","branch","active","can_manage_products","can_stock_movement","can_view_reports","can_manage_masters","can_view_audit_logs","can_manage_users"])if(Object.prototype.hasOwnProperty.call(changes,k))allowed[k]=changes[k];allowed.updated_at=new Date().toISOString();const{error}=await s.from("employee_profiles").update(allowed).eq("user_id",userId);if(error)throw error;return true}

async function currentActor(){
  const s=getSupabase();
  try{
    if(s){const{data}=await s.auth.getUser();if(data?.user){const p=await fetchEmployeeProfile(data.user.id);return{actor:p?.full_name||data.user.email||"Unknown",actor_user_id:data.user.id}}}
  }catch{}
  try{const r=await fetch("/api/session",{credentials:"same-origin",cache:"no-store"});if(r.ok){const d=await r.json();return{actor:d?.user?.username||"Unknown",actor_user_id:null}}}catch{}
  return{actor:"Unknown",actor_user_id:null};
}
async function appendAudit(entry){
  const s=getSupabase(); if(!s)return false;
  try{
    const identity=entry.actor?{actor:entry.actor,actor_user_id:entry.actor_user_id||null}:await currentActor();
    const payload={actor:String(identity.actor||"Unknown"),actor_user_id:identity.actor_user_id||null,action:String(entry.action||"UNKNOWN"),entity_type:String(entry.entity_type||"inventory"),entity_id:String(entry.entity_id||""),entity_name:String(entry.entity_name||""),branch:String(entry.branch||""),old_value:entry.old_value??null,new_value:entry.new_value??null,details:String(entry.details||"")};
    const{error}=await s.from("audit_logs").insert(payload); if(error)throw error; return true;
  }catch(err){console.error("Error writing audit log:",err);return false}
}

export async function fetchProductsFromDB(){const s=getSupabase();if(!s)return null;try{const{data,error}=await s.from("products").select("*").order("created_at",{ascending:true});if(error)throw error;return data||[]}catch(err){console.error("Error fetching products from Supabase:",err);return null}}
export async function upsertProductToDB(product){const s=getSupabase();if(!s)return false;try{const payload={id:product.id,name:product.name,brand:product.brand||"",category:product.category||"",unit:product.unit||"Nos",purchase:Number(product.purchase)||0,sale:Number(product.sale)||0,min:Number(product.min)||5,bangalore:Number(product.bangalore)||0,hosur:Number(product.hosur)||0};const{data:existing,error:readError}=await s.from("products").select("*").eq("id",payload.id).maybeSingle();if(readError)throw readError;const{error}=await s.from("products").upsert(payload);if(error)throw error;await appendAudit({action:existing?"PRODUCT_UPDATED":"PRODUCT_ADDED",entity_type:"product",entity_id:payload.id,entity_name:payload.name,branch:"All",old_value:existing||null,new_value:payload,details:existing?"Product details or stock balance updated":"New product added"});return true}catch(err){console.error("Error saving product to Supabase:",err);return false}}
export async function deleteProductFromDB(id){const s=getSupabase();if(!s)return false;try{const{data:existing,error:readError}=await s.from("products").select("*").eq("id",id).maybeSingle();if(readError)throw readError;const{error}=await s.from("products").delete().eq("id",id);if(error)throw error;await appendAudit({action:"PRODUCT_DELETED",entity_type:"product",entity_id:id,entity_name:existing?.name||id,branch:"All",old_value:existing||null,new_value:null,details:"Product deleted from catalog"});return true}catch(err){console.error("Error deleting product from Supabase:",err);return false}}
export async function fetchMovementsFromDB(){const s=getSupabase();if(!s)return null;try{const{data,error}=await s.from("movements").select("*").order("timestamp",{ascending:false});if(error)throw error;return data||[]}catch(err){console.error("Error fetching movements from Supabase:",err);return null}}
export async function upsertMovementToDB(movement){const s=getSupabase();if(!s)return false;try{const payload={id:movement.id,timestamp:movement.timestamp||movement.id,date:movement.date,type:movement.type,productId:movement.productId||"",product:movement.product||"",branch:movement.branch||"Bangalore",qty:Number(movement.qty)||0,note:movement.note||""};const{data:existing,error:readError}=await s.from("movements").select("*").eq("id",payload.id).maybeSingle();if(readError)throw readError;const{error}=await s.from("movements").upsert(payload);if(error)throw error;await appendAudit({action:existing?"MOVEMENT_UPDATED":payload.type==="OUT"?"STOCK_OUT":"STOCK_IN",entity_type:"movement",entity_id:String(payload.id),entity_name:payload.product,branch:payload.branch,old_value:existing||null,new_value:payload,details:existing?"Stock movement edited":`${payload.type} ${payload.qty} ${payload.product}`});return true}catch(err){console.error("Error saving movement to Supabase:",err);return false}}
export async function deleteMovementFromDB(id){const s=getSupabase();if(!s)return false;try{const{data:existing,error:readError}=await s.from("movements").select("*").eq("id",id).maybeSingle();if(readError)throw readError;const{error}=await s.from("movements").delete().eq("id",id);if(error)throw error;await appendAudit({action:"MOVEMENT_DELETED",entity_type:"movement",entity_id:String(id),entity_name:existing?.product||String(id),branch:existing?.branch||"",old_value:existing||null,new_value:null,details:"Stock movement deleted and stock balance reversed"});return true}catch(err){console.error("Error deleting movement from Supabase:",err);return false}}
export async function fetchAuditLogsFromDB(limit=500){const s=getSupabase();if(!s)return null;try{const{data,error}=await s.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(limit);if(error)throw error;return data||[]}catch(err){console.error("Error fetching audit logs:",err);return null}}
export async function writeAuditLogToDB(entry){return appendAudit(entry)}
export async function fetchMastersFromDB(){const s=getSupabase();if(!s)return null;try{const[bRes,cRes,uRes]=await Promise.all([s.from("brands").select("name"),s.from("categories").select("name"),s.from("units").select("name")]);return{brands:bRes.data?bRes.data.map(i=>i.name):null,categories:cRes.data?cRes.data.map(i=>i.name):null,units:uRes.data?uRes.data.map(i=>i.name):null}}catch(err){console.error("Error fetching masters from Supabase:",err);return null}}
export async function saveMasterItemToDB(table,name){const s=getSupabase();if(!s)return false;try{const{error}=await s.from(table).upsert({name});if(error)throw error;return true}catch(err){console.error(`Error saving to ${table} in Supabase:`,err);return false}}
export async function deleteMasterItemFromDB(table,name){const s=getSupabase();if(!s)return false;try{const{error}=await s.from(table).delete().eq("name",name);if(error)throw error;return true}catch(err){console.error(`Error deleting from ${table} in Supabase:`,err);return false}}
export async function syncAllLocalToDB({products,movements,brands,categories,units}){const s=getSupabase();if(!s)throw new Error("Supabase is not configured yet.");if(brands?.length)await s.from("brands").upsert(brands.map(name=>({name})));if(categories?.length)await s.from("categories").upsert(categories.map(name=>({name})));if(units?.length)await s.from("units").upsert(units.map(name=>({name})));if(products?.length)await s.from("products").upsert(products.map(p=>({id:p.id,name:p.name,brand:p.brand||"",category:p.category||"",unit:p.unit||"Nos",purchase:Number(p.purchase)||0,sale:Number(p.sale)||0,min:Number(p.min)||5,bangalore:Number(p.bangalore)||0,hosur:Number(p.hosur)||0})));if(movements?.length)await s.from("movements").upsert(movements.map(m=>({id:m.id,timestamp:m.timestamp||m.id,date:m.date,type:m.type,productId:m.productId||"",product:m.product||"",branch:m.branch||"Bangalore",qty:Number(m.qty)||0,note:m.note||""})));return true}
