import { createSession, isAuthConfigured, passwordMatches, sessionCookie, usernameMatches } from "./refurbished-auth.js";
function cleanUsername(value){return String(value||"").trim().toLowerCase().replace(/[^a-z0-9._-]/g,"")}
export default async function handler(req,res){
 res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
 const{username="",password=""}=req.body||{};
 if(isAuthConfigured()&&usernameMatches(username)&&passwordMatches(password)){const user={username:String(username).trim(),full_name:"Administrator",role:"admin",branch:"Both",mode:"admin",permissions:{can_manage_products:true,can_stock_movement:true,can_view_reports:true,can_manage_masters:true,can_view_audit_logs:true,can_manage_users:true}};res.setHeader("Set-Cookie",sessionCookie(createSession(user)));return res.status(200).json({authenticated:true,mode:"admin",user});}
 const loginId=cleanUsername(username);const url=String(process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL||"").replace(/\/$/,"");const anonKey=process.env.VITE_SUPABASE_ANON_KEY||"";const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY||"";const emailMap={admin:"admin@hertznbytes.com",administrator:"admin@hertznbytes.com",ganesan:"ganesan@hertznbytes.com",blorestock:"blorestock@hnbt.local",dakshinamoorthi:"dakshinamoothi@hnbt.local"};if(!loginId||!password||!url||!anonKey||!serviceKey)return res.status(401).json({error:"Invalid username or password"});
 try{const tokenResp=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:anonKey,"Content-Type":"application/json"},body:JSON.stringify({email:(emailMap[loginId]||(String(username).includes("@")?String(username).trim().toLowerCase():`${loginId}@hnbt.local`)),password:String(password)})});const tokenData=await tokenResp.json().catch(()=>({}));if(!tokenResp.ok||!tokenData?.user?.id)return res.status(401).json({error:"Invalid username or password"});
 const profileResp=await fetch(`${url}/rest/v1/employee_profiles?user_id=eq.${encodeURIComponent(tokenData.user.id)}&select=*`,{headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`}});const profiles=await profileResp.json().catch(()=>[]);const profile=Array.isArray(profiles)?profiles[0]:null;if(!profile||profile.active===false)return res.status(403).json({error:"This employee account is disabled"});
 const user={user_id:tokenData.user.id,username:loginId,full_name:profile.full_name||loginId,role:profile.role||"employee",branch:profile.branch||"Both",mode:"employee",permissions:{can_manage_products:Boolean(profile.can_manage_products),can_stock_movement:Boolean(profile.can_stock_movement),can_view_reports:Boolean(profile.can_view_reports),can_manage_masters:Boolean(profile.can_manage_masters),can_view_audit_logs:Boolean(profile.can_view_audit_logs),can_manage_users:Boolean(profile.can_manage_users)},force_password_change:Boolean(tokenData.user?.user_metadata?.force_password_change)};res.setHeader("Set-Cookie",sessionCookie(createSession(user)));return res.status(200).json({authenticated:true,mode:"employee",user:{...user,user_id:undefined}});
 }catch{return res.status(401).json({error:"Invalid username or password"});}
}
